# Generated by Django 2.0.2 on 2018-02-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('n', 'no-binary'), ('m', 'male'), ('f', 'female')], max_length=1, verbose_name='gender'),
        ),
    ]
