# Generated by Django 2.0.2 on 2018-05-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_suspend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('no-binary', 'No-binary'), ('male', 'Male'), ('female', 'Female')], default='no-binary', max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email must be unique.'}, max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
